export enum HttpErrorCode {
    UNDEFINED = 1,
    UNHANDLED = 100,
    DOMAIN_ENTITY_VALIDATION = 300,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 403,
    RESOURCE_NOT_FOUND = 404,
    FORBIDDEN = 401,
    INTERNAL_SERVER_ERROR = 500,
    DOMAIN_EVENTS_VALIDATION_EXCEPTION = 600,
}
